### ISSUE TITLE
Add features: task 3

### ISSUE THREAD

**Issue by HalfSealHalfCat** [AlekhinKirill/infa#1]
[In task 3](https://github.com/AlekhinKirill/infa/tree/master/lab3)

1. Add multiple unicorns (at least 5) with the option to select the size, major colour, transparency.
2. Provide more complicated sum shape, e.g. use a curved line and some rays.
3. Add colour option to your apples and leaves.

**Comment by HalfSealHalfCat** [comment]
> [In task 3](https://github.com/AlekhinKirill/infa/tree/master/lab3)
> 
> 1. Add multiple unicorns (at least 5) with the option to select the size, major colour, transparency.
> 2. Provide more complicated sum shape, e.g. use a curved line and some rays.
> 3. Add colour option to your apples and leaves.

It remains unsolved:
1. Curved lines in the sun boundary
2. Objects transparency.

**Comment by AlekhinKirill** [comment]
In task 3
1. Curved line in the sun boundary was added [https://github.com/AlekhinKirill/infa/blob/master/lab3/pictures/unicorns_day.png](url)
string 105 in code 
[https://github.com/AlekhinKirill/infa/blob/master/lab3/codes/unicorn_pict_code.py](url)
2. It was created a special file to demonstrate objects transparency 
[https://github.com/AlekhinKirill/infa/blob/master/lab3/pictures/night_unicorns.png](url)
its code (string 8, 117, 118 create transparency)
[https://github.com/AlekhinKirill/infa/blob/master/lab3/codes/unicorns_night_code.py](url)

**Comment by AlekhinKirill** [comment]
![night_unicorns](https://user-images.githubusercontent.com/71757600/94999909-55233900-05c5-11eb-95ff-0f85ce9f5e4e.png)
![Uploading unicorns_day.png…]()

**Comment by AlekhinKirill** [comment]
![unicorns_day](https://user-images.githubusercontent.com/71757600/94999938-7d129c80-05c5-11eb-9fb7-84fff510c5fc.png)

**Comment by AlekhinKirill** [comment]
In task 3

1.Curved line in the sun boundary was added (second picture)
string 105 in code(see repository unicorns_pict)
2.It was created a special file to demonstrate objects transparency (first picture)
its code(see repository night_unicorns) (string 8, 117, 118 create transparency)

**Comment by TsimboyOlya** [comment]
Accepted.
