### ISSUE TITLE
Add changes: lab 4

### ISSUE THREAD

**Issue by HalfSealHalfCat** [AlekhinKirill/infa#2]
1. Look at the [examples of docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) and rewrite yours in the same way.
2. Use math module for some constants.

**Comment by AlekhinKirill** [comment]
1. Documentation was rewriten in the same way as in your file (but in Russian)
2. Module muth is used in code (string 3, string 25)
